language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
 - ./configure && make && make install
 - echo "extension = simplefork.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - ./runtest.sh

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

